### ISSUE TITLE
Dataset of Cahn_Hilliard equation

### ISSUE THREAD

**Issue by menggedu** [vmattey/bc-PINN#1]
I'm trying to generate the dataset of the 2d Cahn-Hilliard equation, but it does not work with current parameters.  In your paper, the spatial domain is discretized into a grid containing 64 points along each axis, whereas, the temporal domain is discretized into 101
grid points. And alpha is equal to 0.02. However, it turns out to be unreasonable results. Can you help me with that?

**Comment by vmattey** [comment]
Firstly make sure that your spatial and time domain are correct. I have taken the time domain to be very small and the paper mentioned below outlines the procedure for generating the numerical solution.

Physical, mathematical, and numerical derivations of the Cahn–Hilliard equation
https://www.sciencedirect.com/science/article/pii/S0927025613004801

I have exactly used the method they have proposed and obtained good reasonable results for the cahn hilliard equation.
