### ISSUE TITLE
Cahn Hillard Equations

### ISSUE THREAD

**Issue by hengshanmoda** [vmattey/bc-PINN#2]
Hello, nice to meet you. I‘m a beginner of PINN. I recently read you papaer "A Novel Sequential Method to Train Physics Informed Neural
Networks for Allen Cahn and Cahn Hilliard Equations", and find it's a huge progress for PINN. Can you provide the code that solved the Cahn Hillard Equatiions for me to study. 
    Thank you.
    My mailbox is: hengshanmoshibo@gmail.com
    I'm looking forward to your reply.

**Comment by menggedu** [comment]
> I would like to learn the numerical solution of cahn hillard equaitons. Have you obtained the datasets?

**Comment by hengshanmoda** [comment]
Sorry, I don't have the CH equation dataset too, I'm just a beginner of PINN.

**Comment by vmattey** [comment]
I have used chebfun to obtain the datasets for both 1D Allen Cahn and Cahn Hilliard equations. 

Chebfun reference: https://www.chebfun.org/examples/pde/index.html

The chebfun website gives detailed instructions for generating the required datasets.

**Comment by hengshanmoda** [comment]
It's useful for me,thank you for your sharing.
